### ISSUE TITLE
Simulating a bonus to rolling on a table?

### ISSUE THREAD

**Issue by sheibeck** [derikb/rpg-table-randomizer#36]
I'm trying to figure out how I would simulate having a bonus when rolling on a table? For example, when rolling on table A, add +1 bonus if your character is an Elf.

**Comment by derikb** [comment]
Hmm... that is not something I ever thought about. Been pretty focused on tables that have no external variability like that. It's a little tricky because since the tables aren't exactly based on specific numbers, `+1` doesn't really have a meaning. That also implies an ordering where "higher = better" (or "higher = worse", I guess) and the ordering of the result in a specific subtable at this point has no real meaning.

I think there'd have to be another setting for the tables to make order meaningful... and probably some kind of mapping to specific numeric values to specific table results. Then the selecting process wouldn't be about the value relative weights but about passing in a die roll (and likely, having a default die roll on the table). Then we'd also have to account for rolls that go "off the table" (too high/low).

Maybe just mapping subtable results to specific numeric ranges would be enough (as opposed to a weight property). Probably need some way to pass in a die roll token then.

**Comment by sheibeck** [comment]
Yup, all that makes sense. I just wanted to make sure there wasn't something I was missing. I also was thinking about dynamic table weights. Adjust the weights would simulate this a bit. I didn't think about the whole higher being better factor here. This is definitely a rogue element for what I'm doing. It's a helper app for a game that bought that uses tables for everything.

In case your interested in checking out how I'm using your stuff, you can find my repo at https://github.com/sheibeck/fiveparsecscompanion

Thanks for taking the time to respond.

**Comment by derikb** [comment]
Another thing you could do is just use the dice roller to get a random number (modified however you like) and then just use that number to pick from an array of options (assuming its a simple table).

**Comment by sheibeck** [comment]
I came to the same conclusion. Not sure why I didn't think of it sooner.

**Comment by derikb** [comment]
Add #57 as a future feature... ordered tables that can be selected from (by number) or rolled on (via dice token). Closing this issue.
